name: CI

on: [push, pull_request, release]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, macos-latest, windows-2016]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@ranisalt'
    - run: yarn install
      env:
        CI: true
    - run: yarn test
      if: github.event_name == 'push' || github.event_name == 'pull_request'
    - run: yarn publish
      if: github.event_name == 'release'
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
